# Generated by Django 6.0.4 on 2026-04-28 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "url"], name="links_bookmark_user_url_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-updated_at"], name="links_bm_user_updated_idx"
            ),
        ),
    ]
