# Generated by Django 6.0.4 on 2026-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="shared",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="toread",
            field=models.BooleanField(default=False),
        ),
    ]
