# Generated by Django 6.0.4 on 2026-04-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_add_shared_toread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
